Тема “Вычисления с помощью Numpy”

In [2]:
# Устанавливаем пакет, если он не установлен
# !pip install numpy
import numpy as np

In [3]:
# Задание 1
# Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк
# и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6,
# 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение.
# Затем найдите среднее значение по каждому признаку, используя метод mean массива
# Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [5]:
first_column = np.array([1, 2, 3, 3, 1]).reshape(5, -1)
second_column = np.array([6, 8, 11, 10, 7]).reshape(5, -1)
a = np.hstack((first_column, second_column))
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [6]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

In [ ]:
# Задание 2
# Вычислите массив a_centered, отняв от значений массива “а” средние значения
# соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно
# производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [7]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [ ]:
# Задание 3
# Найдите скалярное произведение столбцов массива a_centered. В результате должна
# получиться величина _centered_spa. Затем поделите a_centered_sp на N-1, где N - число
# наблюдений.

In [8]:
a_centered[:, 0]

array([-1.,  0.,  1.,  1., -1.])

In [9]:
# Вычислим скалярное произведение двух столбцов
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
# Вычислим количество наблюдений (сколько у нас строк)
N = a_centered.shape[0]
# Вычислим результат
result = a_centered_sp / (N - 1)   
result

2.0

Тема “Работа с данными в Pandas”

In [11]:
# Устанавливаем пакет, если он не установлен
# !pip install pandas
import pandas as pd

In [ ]:
# Задание 1
# Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со
# столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и
# ['Тургенев', 'Чехов', 'Островский'].
# Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно
# содержатся данные:
# [1, 1, 1, 2, 2, 3, 3],
# ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и
# поклонники']
# Нужны prices!
# [500, 400, 300, 350, 450, 600, 200]

In [12]:
# Создадим датафрейм autohors
authors = pd.DataFrame()
authors['author_id'] = [1, 2, 3]
authors['author_name'] = ['Тургенев', 'Чехов', 'Островский']
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [13]:
# Создадим датафрейм book
book = pd.DataFrame()
book['author_id'] = [1, 1, 1, 2, 2, 3, 3]
book['book_title'] = ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники']
book['price'] = [500, 400, 300, 350, 450, 600, 200]
book

author_id            book_title  price
0          1           Отцы и дети    500
1          1                 Рудин    400
2          1     Дворянское гнездо    300
3          2      Толстый и тонкий    350
4          2       Дама с собачкой    450
5          3                 Гроза    600
6          3  Таланты и поклонники    200

In [ ]:
# Задание 2
# Получите датафрейм authors_price, соединив дата фреймы authors и books по полю author_id.

In [14]:
# Соединим две таблицы по столбцу 'author_id'
authors_price = pd.merge(authors, book, on='author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    500
1          1    Тургенев                 Рудин    400
2          1    Тургенев     Дворянское гнездо    300
3          2       Чехов      Толстый и тонкий    350
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    600
6          3  Островский  Таланты и поклонники    200

In [ ]:
# Задание 3
# Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими
# книгами.

In [15]:
top5 = authors_price.sort_values(by="price", ascending=False).head(5)
top5

author_id author_name        book_title  price
5          3  Островский             Гроза    600
0          1    Тургенев       Отцы и дети    500
4          2       Чехов   Дама с собачкой    450
1          1    Тургенев             Рудин    400
3          2       Чехов  Толстый и тонкий    350

In [ ]:
# Задание 4
# Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat
# должны быть четыре столбца:
# author_name, min_price, max_price и mean_price,
# в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя
# цена на книги этого автора.

In [23]:
# Создаём датафрейм
authors_stat = pd.DataFrame()
# Группируем по авторам и вычислям 'min', 'max', 'mean' по столбцу 'price'
authors_stat = authors_price.groupby("author_name").agg({'price':['min', 'max', 'mean']})

In [22]:
# Фамилия автора это индекс, переведём индекс в колонку
authors_stat.reset_index(inplace=True)
# Сделаем из вложенных колонок одну
authors_stat['min_price'] = authors_stat['price']['min']
authors_stat['max_price'] = authors_stat['price']['max']
authors_stat['mean_price'] = authors_stat['price']['mean']
# Удалим не нужную колонку
authors_stat.drop('price', axis=1, inplace=True)
authors_stat

/var/folders/qc/lvhfx_2j5vx1d8z22hvjhx400000gn/T/ipykernel_45958/4136075712.py:8: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  authors_stat.drop('price', axis=1, inplace=True)


author_name min_price max_price mean_price
                                            
0  Островский       200       600      400.0
1    Тургенев       300       500      400.0
2       Чехов       350       450      400.0